spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/university-scheduler
    username: postgres
    password: postgres
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
  liquibase:
    change-log: classpath:db/university-scheduler-changelog.xml