spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/university-scheduler
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false