server:
  port: ${PORT:8080}
keycloak:
  realm: university-scheduler-realm
  auth-server-url: http://localhost:8087/auth
  resource: university-scheduler
  public-client: true
  bearer-only: true
  credentials:
    secret: K38CvXIgBEP3uRnNO42QNWRNhJ2bP4r0
  ssl-required: none
spring:
  datasource:
    url: jdbc:${DATABASE_URL:postgresql://localhost:5433/university-scheduler}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:postgres}
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
  liquibase:
    change-log: classpath:db/university-scheduler-changelog.xml
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${keycloak.auth-server-url}/realms/${keycloak.realm}
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs